# Generated by Django 4.1.2 on 2022-10-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
